Ged
Eduard-Gimaev/test-guru pull request #4
Opened 2023-08-16 16:46 UTC by Eduard-Gimaev

2023-08-21 07:30 UTC, BubuntuClu requested changes

2023-08-21 07:30 UTC, BubuntuClu commented on db/migrate/20230819051844_add_user_id_to_test.rb
> +    add_reference :tests, :user, foreign_key: true, null: false
для чего эта связь?

2023-08-21 07:30 UTC, BubuntuClu commented on db/migrate/20230815093950_create_users.rb
> +      t.string :user, null: false
файл с этой миграцией уже смержен. значит что его нельзя править, правки вносить только через новые миграции.
надо откатить это изменение и создать миграцию

2023-08-21 07:30 UTC, BubuntuClu commented on app/models/user.rb
> +    Test.where(level: level).order(title: :desc).pluck(:title)
в этом запросе никак не участвует пользователь, надо находить прохождения пользователя по уровню тестов

2023-08-21 09:10 UTC, Eduard-Gimaev commented on db/migrate/20230819051844_add_user_id_to_test.rb
> +    add_reference :tests, :user, foreign_key: true, null: false
Делал, в процессе вывода инфы по заданию , потом забыл удалить . Поправлю

2023-08-21 09:15 UTC, Eduard-Gimaev commented on db/migrate/20230815093950_create_users.rb
> +      t.string :user, null: false
done!

2023-08-21 17:46 UTC, BubuntuClu requested changes

2023-08-21 17:46 UTC, BubuntuClu commented on db/migrate/20230815093950_create_users.rb
> +      t.string :user, null: false
этот код не удалил. тут все еще есть изменение в этом файле

2023-09-10 17:08 UTC, BubuntuClu requested changes

2023-09-10 17:08 UTC, BubuntuClu commented on app/models/user.rb
> +    TestsUser.joins('JOIN tests ON tests.id = tests_users.test_id').joins('JOIN users ON users.id = tests_users.user_id').where(user_id: self).where('tests.level = ?', level).pluck(:user, :title)
`.where(user_id: self)` ты передаешь объект, а не int поле. попробуй указать id пользователя

2023-09-12 10:55 UTC, merged