Scope valid
Eduard-Gimaev/test-guru pull request #6
Opened 2023-09-17 16:58 UTC by Eduard-Gimaev

2023-09-17 18:09 UTC, BubuntuClu requested changes

2023-09-17 18:09 UTC, BubuntuClu commented on app/models/answer.rb
> +    validates :validate_answers_count, on: :create
кастомные валидации задаются словом `validate`

2023-09-17 18:09 UTC, BubuntuClu commented on app/models/answer.rb
> +       errors.add(:base, "One Question can have from 1 to 4 answers.") if question.answers.count >= 4
в тексте ошибки стоит убрать минимальное значение, так как это не совсем правда

2023-09-17 18:09 UTC, BubuntuClu commented on app/models/test.rb
> +  scope :by_category, -> (category_title) {joins(:category).where('categories.title = ?', category_title)}
`where(categories: { title: category_title })`
давай в более рубишном стиле запишем

2023-09-17 18:09 UTC, BubuntuClu commented on app/models/test.rb
> +  validates :title, presence: true
нужно добавить еще валидацию уникальности пары название+уровень. это можно сделать через опцию у `validates`

2023-09-17 18:09 UTC, BubuntuClu commented on app/models/test.rb
> +  validates :title, presence: true
и надо не забыть добавить составной уникальный индекс в БД на эти поля

2023-09-18 10:42 UTC, Eduard-Gimaev commented on app/models/answer.rb
> +    validates :validate_answers_count, on: :create
поправил

2023-09-18 10:43 UTC, Eduard-Gimaev commented on app/models/answer.rb
> +       errors.add(:base, "One Question can have from 1 to 4 answers.") if question.answers.count >= 4
поправил

2023-09-18 10:46 UTC, Eduard-Gimaev commented on app/models/test.rb
> +  scope :by_category, -> (category_title) {joins(:category).where('categories.title = ?', category_title)}
done

2023-09-18 11:10 UTC, Eduard-Gimaev commented on app/models/test.rb
> +  validates :title, presence: true
added

2023-09-18 11:10 UTC, Eduard-Gimaev commented on app/models/test.rb
> +  validates :title, presence: true
Добавил  для тестов и для юзеров

2023-09-18 17:31 UTC, BubuntuClu commented on db/migrate/20230918105831_add_index_to_users.rb
> +    add_column :users, :email, :string, default: "", null: false
тут могут ошибки сыпаться. ты добавляешь дефолтное значение и у тебя есть уникальный индекс. как только вторая запись с дефолтным значением будет попадать в БД будешь ловить ошибку индекса. зачем дефолтное значение на поле почты?

2023-09-21 05:01 UTC, merged