Rest
Eduard-Gimaev/test-guru pull request #7
Opened 2023-09-27 05:47 UTC by Eduard-Gimaev

2023-09-27 08:43 UTC, BubuntuClu requested changes

2023-09-27 08:43 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @question = @test.questions.create(question_params)
Параметры с фронта могут быть не валидные, это надо учитывать
```
question = @test.questions.new(questions_params)
if question.save
  Render good
else
  Render bad
end
```

2023-09-27 08:43 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    params.require(:question).permit(:body, :test_id)
`test_id` не надо указывать. ты создаешь объект через ассоциацию

2023-09-27 08:43 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +  rescue_from ActiveRecord::RecordNotFound, with: :rescue_question_not_found
это стоит поместить в начало файла, иначе не будет поянтно что происходит, так как обработчик спрятан в недрах кода

2023-09-27 08:43 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    @test = Test.create(test_params)
тут тоже надо проверять что объект создался

2023-09-27 08:43 UTC, BubuntuClu commented on bin/yarn
> +  yarn = ENV['PATH'].split(File::PATH_SEPARATOR)
правки рубокопа надо выносить в отдельные ПРы. сейчас тут куча "мусора", которая отвлекает от того что сделал ты

2023-09-27 08:43 UTC, BubuntuClu commented on app/views/tests/index.html.erb
> +  <%= render @tests %>
у тебя тут код падать кажется будет. у тебя нет вьюхи под этот код

2023-09-28 10:34 UTC, Eduard-Gimaev commented on app/controllers/questions_controller.rb
> +    @question = @test.questions.create(question_params)
done

2023-09-28 10:39 UTC, Eduard-Gimaev commented on app/controllers/questions_controller.rb
> +    params.require(:question).permit(:body, :test_id)
done, but...
Да, именно так и должно быть,  я бился с этим  пару дней, не работало изначально создание вопросов, пока не добавил test_id, а сейчас без этого создается, что произошло и почему стало работать не понял честно говоря , ассоцияция же всегда была и не менялась, мистика или приходит просто с опытом замечать детали

2023-09-28 10:46 UTC, Eduard-Gimaev commented on app/controllers/questions_controller.rb
> +  rescue_from ActiveRecord::RecordNotFound, with: :rescue_question_not_found
done, I actually tried not to forget it, but in the end it just slipped my mind....

2023-09-28 10:46 UTC, Eduard-Gimaev commented on app/controllers/tests_controller.rb
> +    @test = Test.create(test_params)
done

2023-09-28 10:48 UTC, Eduard-Gimaev commented on bin/yarn
> +  yarn = ENV['PATH'].split(File::PATH_SEPARATOR)
могу так оставить пока? больше не буду без указаний рубокопом рефакторить код

2023-09-29 06:53 UTC, Eduard-Gimaev commented on app/views/tests/index.html.erb
> +  <%= render @tests %>
done

2023-09-29 07:11 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
>      @question = @test.questions.create(question_params)
`create` надо заменить на `new`. `create` под капотом вызывает сохранение объекта в БД. потом ты вызываешь `save`, что тоже сохраняет объект в БД. то есть ты делаешь на одну лишнюю операцию в БД

2023-09-29 07:11 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    @test = Test.create(test_params)
тоже самое что и в вопросе

2023-09-29 07:12 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    params.require(:question).permit(:bodys)
https://github.com/Eduard-Gimaev/test-guru/blob/main/db/schema.rb#L31

у тебя нет такого поля в вопросе. оно не будет сохранено

2023-09-29 14:55 UTC, merged