Logic
Eduard-Gimaev/test-guru pull request #9
Opened 2023-10-11 14:47 UTC by Eduard-Gimaev

2023-10-11 17:43 UTC, BubuntuClu requested changes

2023-10-11 17:43 UTC, BubuntuClu commented on app/controllers/answers_controller.rb
> +    @answer = Answer.new(answer_params)
создавай ответ от ассоциации вопроса, как в `new` методе

2023-10-11 17:43 UTC, BubuntuClu commented on app/controllers/answers_controller.rb
> +    params.require(:answer).permit(:body, :correct, :question_id)
параметр `question_id` лишний. создавай через ассоацию. более рельсово

2023-10-11 17:43 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +  before_action :set_user, only: :start
выбери один стиль написания методов. `find_/set_` делат по сути одно и тоже, но глагол используешь разный. `set` в рубях не очень приветствуется

2023-10-11 17:43 UTC, BubuntuClu commented on app/models/test_passage.rb
> +  before_validation :before_validation_set_current_question, on: %i[create update]
вкусовщина, но я не очень понимаю зачем писать имя колбэка в метод, который он вызвает

2023-10-11 17:43 UTC, BubuntuClu commented on app/views/test_passages/result.html.erb
> +      <% else %>
чет отступы пляшут в файле

2023-10-11 17:43 UTC, BubuntuClu commented on app/views/tests/index.html.erb
> +  <caption>TESTS:</caption>
тут тоже отступы

2023-10-11 17:43 UTC, BubuntuClu commented on db/migrate/20230918105831_add_index_to_users.rb
> +    add_column :users, :email, :string
атата, нельзя править миграции смерженные в мастер. откати изменение в файле и сделай новую миграцию

2023-10-11 17:43 UTC, BubuntuClu commented on db/migrate/20231008140832_drop_table_tests_users.rb
> +  def up
если есть метод `up`, то должен быть и метод `down`, чтобы при откатывании миграции не словить ошибку.
в данном случае, метод `down` можно оставить пустым

2023-10-14 16:18 UTC, Eduard-Gimaev commented on app/models/test_passage.rb
> +  before_validation :before_validation_set_current_question, on: %i[create update]
это была рекомендация из скринкаста

2023-10-15 09:17 UTC, Eduard-Gimaev commented on db/migrate/20230918105831_add_index_to_users.rb
> +    add_column :users, :email, :string
Не специально, разобрался поправил, ловил ошибку при откате не мог понять, что происходит, а просто в БД уже были записаны данные без email. Поправил вообщем

2023-10-17 10:53 UTC, merged